// ════════════════════════════════════════════════════════════
//  ONE-TIME SEED ROUTE  —  GET /api/seed-questions?key=SEED_MOCKMATE_2024
//  Visit this URL once after deploying to Render, then remove the require() line from server.js
// ════════════════════════════════════════════════════════════
const Question = require('./models/QuestionSchema');

const SEED_DATA = [
  { questionType:'text', category:'Data Structures & Algorithms', subcategory:'Sorting', difficulty:'medium', type:'technical', text:'Explain QuickSort algorithm, its average and worst-case time complexity, and when you would avoid using it.', keyPoints:['Divide and conquer','Pivot selection','Average O(n log n)','Worst case O(n²) on sorted input','In-place sorting'], tags:['sorting','quicksort','complexity'], timeLimit:180 },
  { questionType:'text', category:'Operating Systems', subcategory:'Process Management', difficulty:'hard', type:'technical', text:"What are the four necessary conditions for deadlock? Explain how the Banker's algorithm prevents deadlock.", keyPoints:['Mutual exclusion','Hold and wait','No preemption','Circular wait','Safe state'], tags:['deadlock','os','banker'], timeLimit:240 },
  { questionType:'text', category:'Database Management Systems', subcategory:'Normalization', difficulty:'medium', type:'technical', text:'Explain 1NF, 2NF, and 3NF with examples. Why is normalization important?', keyPoints:['1NF: atomic values','2NF: no partial dependency','3NF: no transitive dependency','Reduces redundancy'], tags:['normalization','dbms','sql'], timeLimit:210 },
  { questionType:'text', category:'System Design', subcategory:'Distributed Systems', difficulty:'hard', type:'system_design', text:'Design a URL shortener like bit.ly. Discuss database schema, hashing strategy, caching, and how to handle 100M URLs at scale.', keyPoints:['Base62 encoding','Key-value store','Redis caching','Load balancer','Database sharding'], timeLimit:600 },
  { questionType:'text', category:'Computer Networks', subcategory:'Transport Layer', difficulty:'easy', type:'technical', text:'What is the difference between TCP and UDP? Give real-world use cases for each.', keyPoints:['TCP: connection-oriented, reliable','UDP: connectionless, fast'], tags:['tcp','udp','networking'], timeLimit:150 },
  { questionType:'text', category:'Object-Oriented Programming', subcategory:'Design Principles', difficulty:'medium', type:'technical', text:'Explain the SOLID principles with a real-world example for each.', keyPoints:['Single Responsibility','Open/Closed','Liskov Substitution','Interface Segregation','Dependency Inversion'], tags:['solid','oop'], timeLimit:300 },
  { questionType:'text', category:'Web Development', subcategory:'React', difficulty:'medium', type:'technical', text:'Explain the React component lifecycle. How does useEffect replace lifecycle methods in functional components?', keyPoints:['Mount, update, unmount','useEffect dependencies array','Cleanup function'], tags:['react','hooks','lifecycle'], timeLimit:180 },
  { questionType:'text', category:'Behavioral', difficulty:'easy', type:'behavioral', text:'Tell me about a time you had to debug a complex issue under pressure. What was your approach?', keyPoints:['Problem isolation','Systematic debugging','Root cause analysis'], timeLimit:240 },
  { questionType:'mcq', category:'Data Structures & Algorithms', subcategory:'Trees', difficulty:'easy', type:'technical', text:'What is the time complexity of searching in a balanced Binary Search Tree (BST)?', options:[{text:'O(1)',isCorrect:false},{text:'O(log n)',isCorrect:true},{text:'O(n)',isCorrect:false},{text:'O(n log n)',isCorrect:false}], correctOptionIndex:1, explanation:'In a balanced BST, each comparison halves the search space — O(log n).', tags:['bst','trees','complexity'], timeLimit:60 },
  { questionType:'mcq', category:'Operating Systems', subcategory:'Deadlock', difficulty:'medium', type:'technical', text:'Which of the following is NOT a necessary condition for deadlock?', options:[{text:'Mutual Exclusion',isCorrect:false},{text:'Preemption',isCorrect:true},{text:'Hold and Wait',isCorrect:false},{text:'Circular Wait',isCorrect:false}], correctOptionIndex:1, explanation:'"No Preemption" is required for deadlock, not "Preemption".', tags:['deadlock','os'], timeLimit:60 },
  { questionType:'mcq', category:'Database Management Systems', subcategory:'SQL', difficulty:'easy', type:'technical', text:'Which SQL clause is used to filter groups AFTER a GROUP BY operation?', options:[{text:'WHERE',isCorrect:false},{text:'FILTER',isCorrect:false},{text:'HAVING',isCorrect:true},{text:'BETWEEN',isCorrect:false}], correctOptionIndex:2, explanation:'HAVING filters groups after aggregation. WHERE filters rows before grouping.', tags:['sql','having'], timeLimit:45 },
  { questionType:'mcq', category:'Computer Networks', subcategory:'Transport Layer', difficulty:'easy', type:'technical', text:'What does the acronym "HTTP" stand for?', options:[{text:'HyperText Transfer Protocol',isCorrect:true},{text:'HyperText Transmission Program',isCorrect:false},{text:'High-speed Text Transfer Protocol',isCorrect:false},{text:'Hybrid Transfer Text Protocol',isCorrect:false}], correctOptionIndex:0, explanation:'HTTP = HyperText Transfer Protocol, the foundation of web data communication.', tags:['http','networking'], timeLimit:30 },
  { questionType:'mcq', category:'Data Structures & Algorithms', subcategory:'Graphs', difficulty:'medium', type:'technical', text:'Which data structure is used internally by BFS?', options:[{text:'Stack',isCorrect:false},{text:'Queue',isCorrect:true},{text:'Priority Queue',isCorrect:false},{text:'Hash Map',isCorrect:false}], correctOptionIndex:1, explanation:'BFS uses a Queue (FIFO). DFS uses a Stack.', tags:['bfs','graph','queue'], timeLimit:45 },
  { questionType:'mcq', category:'Object-Oriented Programming', subcategory:'Concepts', difficulty:'easy', type:'technical', text:'Which OOP concept allows a child class to provide a specific implementation of a method already defined in its parent?', options:[{text:'Overloading',isCorrect:false},{text:'Abstraction',isCorrect:false},{text:'Overriding',isCorrect:true},{text:'Encapsulation',isCorrect:false}], correctOptionIndex:2, explanation:'Method Overriding is the basis of runtime polymorphism.', tags:['oop','overriding'], timeLimit:45 },
  { questionType:'mcq', category:'Web Development', subcategory:'JavaScript', difficulty:'medium', type:'technical', text:'What is the output of: console.log(typeof null)?', options:[{text:'"null"',isCorrect:false},{text:'"object"',isCorrect:true},{text:'"undefined"',isCorrect:false},{text:'"boolean"',isCorrect:false}], correctOptionIndex:1, explanation:'typeof null returns "object" — a famous JavaScript quirk from its original implementation.', tags:['javascript','typeof'], timeLimit:45 },
  { questionType:'mcq', category:'Data Structures & Algorithms', subcategory:'Dynamic Programming', difficulty:'hard', type:'technical', text:'Which problem CANNOT be solved optimally with a greedy approach?', options:[{text:'Activity Selection Problem',isCorrect:false},{text:'Fractional Knapsack',isCorrect:false},{text:'0/1 Knapsack Problem',isCorrect:true},{text:"Prim's MST Algorithm",isCorrect:false}], correctOptionIndex:2, explanation:'0/1 Knapsack requires Dynamic Programming. Greedy only works for the Fractional variant.', tags:['greedy','dp','knapsack'], timeLimit:60 },
  { questionType:'coding', category:'Data Structures & Algorithms', subcategory:'Arrays', difficulty:'easy', type:'technical', text:'Two Sum', problemStatement:'Given an array of integers `nums` and an integer `target`, return the **indices** of the two numbers that add up to `target`. Exactly one solution exists.', constraints:['2 <= nums.length <= 10^4','Only one valid answer exists.'], examples:[{input:'nums=[2,7,11,15], target=9',output:'[0,1]',explanation:'nums[0]+nums[1]=9'}], testCases:[{input:'nums=[2,7,11,15] target=9',expectedOutput:'[0,1]',isHidden:false},{input:'nums=[3,2,4] target=6',expectedOutput:'[1,2]',isHidden:false}], expectedTimeComplexity:'O(n)', expectedSpaceComplexity:'O(n)', tags:['array','hash-map'], timeLimit:1800 },
  { questionType:'coding', category:'Data Structures & Algorithms', subcategory:'Stack', difficulty:'easy', type:'technical', text:'Valid Parentheses', problemStatement:'Given a string `s` of bracket characters, determine if the input string is **valid** (every open bracket has a matching close bracket in the right order).', constraints:['1 <= s.length <= 10^4'], examples:[{input:'s="()"',output:'true',explanation:''},{input:'s="(]"',output:'false',explanation:''}], testCases:[{input:'()',expectedOutput:'true',isHidden:false},{input:'(]',expectedOutput:'false',isHidden:false},{input:'{[]}',expectedOutput:'true',isHidden:true}], expectedTimeComplexity:'O(n)', expectedSpaceComplexity:'O(n)', tags:['stack','string'], timeLimit:1800 },
  { questionType:'coding', category:'Data Structures & Algorithms', subcategory:'Linked Lists', difficulty:'easy', type:'technical', text:'Reverse Linked List', problemStatement:'Given the `head` of a singly linked list, reverse the list in-place and return the reversed list.', constraints:['0 <= nodes <= 5000'], examples:[{input:'head=[1,2,3,4,5]',output:'[5,4,3,2,1]',explanation:''}], testCases:[{input:'[1,2,3,4,5]',expectedOutput:'[5,4,3,2,1]',isHidden:false},{input:'[1,2]',expectedOutput:'[2,1]',isHidden:false}], expectedTimeComplexity:'O(n)', expectedSpaceComplexity:'O(1)', tags:['linked-list'], timeLimit:1800 },
  { questionType:'coding', category:'Data Structures & Algorithms', subcategory:'Binary Search', difficulty:'easy', type:'technical', text:'Binary Search', problemStatement:'Given a sorted array `nums` and integer `target`, return the index of target or -1. Must run in **O(log n)**.', constraints:['1 <= nums.length <= 10^4','Sorted in ascending order'], examples:[{input:'nums=[-1,0,3,5,9,12], target=9',output:'4',explanation:'9 exists at index 4'}], testCases:[{input:'[-1,0,3,5,9,12] 9',expectedOutput:'4',isHidden:false},{input:'[-1,0,3,5,9,12] 2',expectedOutput:'-1',isHidden:false}], expectedTimeComplexity:'O(log n)', expectedSpaceComplexity:'O(1)', tags:['binary-search','array'], timeLimit:1800 },
];

module.exports = function registerSeedRoute(app) {
  app.get('/api/seed-questions', async (req, res) => {
    if (req.query.key !== 'SEED_MOCKMATE_2024')
      return res.status(403).json({ success: false, message: 'Forbidden — provide ?key=SEED_MOCKMATE_2024' });
    try {
      const existing = await Question.countDocuments();
      if (existing > 0 && !req.query.force) {
        return res.json({ success: true, message: `Already seeded — ${existing} questions in DB. Add &force=1 to re-seed.`, count: existing });
      }
      if (existing > 0 && req.query.force) {
        await Question.deleteMany({});
      }
      const inserted = await Question.insertMany(SEED_DATA);
      res.json({
        success: true,
        message: `Seeded ${inserted.length} questions successfully!`,
        breakdown: {
          text:   inserted.filter(q => q.questionType === 'text').length,
          mcq:    inserted.filter(q => q.questionType === 'mcq').length,
          coding: inserted.filter(q => q.questionType === 'coding').length,
        },
      });
    } catch (err) {
      res.status(500).json({ success: false, message: err.message });
    }
  });
};
